name: Automatically publish to Modrinth and CurseForge
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: github.repository_owner == 'OneCraftES'
    runs-on: ubuntu-latest
    environment: github-actions
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download and Build packwiz
        run: |
          git clone https://github.com/packwiz/packwiz.git
          cd packwiz
          go build
          chmod +x packwiz
          mv packwiz ..
          cd ..
          rm -rf packwiz

      - name: Set up environment
        run: |
          mkdir -p dist

      - name: Build MultiMC/PrismLauncher Package
        run: |
          cd MultiMC
          zip -r ../dist/OneCraft.Optimized-${{ github.ref_name }}-multimc.zip ./*
          cd ..

      - name: Build CurseForge Package
        run: |
          cd CurseForge
          zip -r ../dist/OneCraft.Optimized-${{ github.ref_name }}-curseforge.zip ./*
          cd ..

      - name: Build Modrinth Package
        run: |
          cd Packwiz/${{ vars.MC_VERSION }}
          ../../packwiz modrinth export -o ../../dist/OneCraft.Optimized-${{ github.ref_name }}.mrpack
          cd ../..

      - name: Generate Attestation
        id: attest-mrpack
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/OneCraft.Optimized-${{ github.ref_name }}.mrpack

      - name: Prepare Attestation Bundle
        run: |
          cp ${{ steps.attest-mrpack.outputs.bundle-path }} dist/cosign-bundle.json
          cd dist
          zip cosign-bundle.zip cosign-bundle.json
          cd ..

      - name: Upload to GitHub Release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: OneCraft.Optimized-${{ github.ref_name }}-all
          path: |
            dist/OneCraft.Optimized-${{ github.ref_name }}-multimc.zip
            dist/OneCraft.Optimized-${{ github.ref_name }}-curseforge.zip
            dist/OneCraft.Optimized-${{ github.ref_name }}.mrpack
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ github.ref_name }} for ${{ vars.MC_VERSION }}
          version: ${{ github.ref_name }}
          version-type: release
          changelog-file: CHANGELOG.md
          curseforge-id: ${{ vars.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: dist/OneCraft.Optimized-${{ github.ref_name }}-curseforge.zip
          loaders: fabric
          game-versions: ${{ vars.MC_VERSION }}
          java: 17

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ github.ref_name }} for ${{ vars.MC_VERSION }}
          version: ${{ github.ref_name }}
          version-type: release
          changelog-file: CHANGELOG.md
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: subset
          files: |
            dist/OneCraft.Optimized-${{ github.ref_name }}.mrpack
            dist/cosign-bundle.zip
          loaders: fabric
          game-versions: ${{ vars.MC_VERSION }}
          java: 17
